name: matrix-analysis-2024
channels:
  - defaults
dependencies:
  - jupyterlab=3.6.3
  - matplotlib=3.8.0
  - numpy=1.26.0
  - pandas=2.1.1
  - python=3.10.13
  - requests=2.31.0
  - scikit-image=0.20.0
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - pip:
    - otter-grader==5.3.0
